#this program will ask for your name and age.
print("Hello world")
print("What is your name?")
myName = input()
print("its good to meet you," + myName)
print("The length of your name is:")
print(len(myName))
print("what is your age ?")
myAge =input()
print()
print('You will be ' + str(int(myAge)+1) +' in a year.')
